name: Node Continuos Integration
on: push
jobs:
  build-node:
    runs-on: macos-latest
    steps:
      - run: node -v
        name: Check Node version
      - run: npm -v
      - uses: actions/checkout@v3
        name: Checkout code from GitHub
      - run: npm i
        name: Install node packages
      - run: node script.js
        name: Run code